# Generated by Django 5.0.3 on 2024-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_starts',
            field=models.IntegerField(choices=[(1, 'Worst'), (1, 'Bad'), (1, 'Not Bad'), (1, 'Good'), (1, 'Excellent')]),
        ),
    ]
